# Description: this workflow runs build mega-apps that have all the connected components.

name: POC / Build System Test Canary

permissions:
  id-token: write # This is required for aws-actions/configure-aws-credentials

on:
  push:
    branches: [fix-vue-build-tests]


jobs:
  build:
    uses: ./.github/workflows/reusable-build-system-test.yml
    with:
      dist-tag: latest