# Description: This workflow runs unit + e2e tests, then publishes UI packages
#              to `@next` NPM tag.
#
# Triggered by: merge to `main`

name: Publish / liveness-omega

concurrency:
  group: e2e-${{ github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [liveness-omega]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  setup-cache:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-setup-cache.yml@main
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  publish:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-tagged-publish.yml@main
    with:
      dist-tag: liveness-omega
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}